apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-benchmark-claim
spec:
  storageClassName: "{{STORAGE_CLASS_NAME}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
