apiVersion: v1
kind: Pod
metadata:
    name: dataaccess
spec:
    containers:
    - name: alpine
      image: alpine:latest
      command: ['sleep', 'infinity']
      volumeMounts:
      - name: mypvc
        mountPath: /spark-benchmark-mount
    volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: spark-benchmark-claim